language: rust
rust:
  - nightly
os: linux
dist: bionic
before_install:
  - sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm
  - cargo install cargo-download
  - cargo install uhyve
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
jobs:
  include:
    - stage: Test
      script:
        - cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit
        # used to get terminal with new groups permissions while preserving own user
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 /home/travis/.cargo/bin/uhyve target/x86_64-unknown-hermit/debug/hello_world"

    -
      script:
        - cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit --release
        - sudo -E sudo -u $USER -E bash -c "HERMIT_VERBOSE=1 /home/travis/.cargo/bin/uhyve target/x86_64-unknown-hermit/release/hello_world"
