name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install qemu/nasm
      run: sudo apt-get update --fix-missing && sudo apt-get install qemu-system-x86 nasm
    - uses: actions/checkout@v1
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Install cargo-download
      run: cargo install cargo-download
    - name: Building dev version
      run:
         cargo build
    - name: Building release version
      run:
         cargo build --release
    - name: Run dev version
      run:
         cargo run
    - name: Run release version
      run:
         cargo run --release
