name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    container:
      image: registry.git.rwth-aachen.de/acs/public/hermitcore/hermitrust
      options: --cpus 2

    steps:
    - uses: actions/checkout@v1
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Install cargo-download
      run: cargo install cargo-download
    - name: Building dev version
      run:
         cargo build
    - name: Building release version
      run:
         cargo build --release
    - name: Run dev version
      run:
         cargo run
    - name: Run release version
      run:
         cargo run --release
